import React, { Suspense } from 'react';
import type { Metadata } from 'next';
import NextTopLoader from 'nextjs-toploader';

import { config } from '@fortawesome/fontawesome-svg-core';
import ScrollTopHolder from '@joy/components/ScrollTopHolder';
import { languages } from '@joy/i18n/config';
import colors from '@joy/theme/colors';
import fonts from '@joy/theme/font';
import ThemeRegistry from '@joy/theme/ThemeRegistry';
import { Language, ParamsWithLng } from '@joy/types/i18n';

import Providers from '../Providers';

import Loading from './loading';

import './globals.css';
import '@fortawesome/fontawesome-svg-core/styles.css';

config.autoAddCss = false;

// revalidate at some frequency
export const revalidate = 600;

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return languages.map((lang: Language) => ({ lang: lang.code }));
}

export default function RootLayout({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
  params: ParamsWithLng;
}) {
  return (
    <html lang={lang} suppressHydrationWarning>
      <body className={fonts.default.className} id='root'>
        <NextTopLoader color={colors.primaryMain} shadow='none' />
        <Providers>
          <main className='flex'>
            <ThemeRegistry>
              <aside className=''>Side bar</aside>
              <ScrollTopHolder>
                <Suspense fallback={<Loading />}>{children}</Suspense>
              </ScrollTopHolder>
            </ThemeRegistry>
          </main>
        </Providers>
      </body>
    </html>
  );
}
