import { Suspense } from 'react';
import type { Metadata } from 'next';
import { config } from '@fortawesome/fontawesome-svg-core';
import './globals.css';
import MuiThemeProvider from '@jsc/theme/MuiThemeProvider';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { ParamsWithLng } from '@jsc/types/i18n';
import Providers from '../Providers';
import ScrollTopHolder from '@jsc/components/ScrollTopHolder';
import Loading from './loading';

import fonts from '@jsc/theme/font';

config.autoAddCss = false;

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// export async function generateStaticParams() {
//   return languages.map((lang: Language) => ({ lang: lang.code }));
// }

export default function RootLayout(
  {
    children,
    params: { lang },
  }: {
    children: React.ReactNode;
    params: ParamsWithLng;
  }) {
  return (
    <html lang={lang} suppressHydrationWarning>
      <body className={fonts.default.variable} id='root'>
        {/*<NextTopLoader color={colors.primaryMain} shadow='none' />*/}
        <Providers>
          <main className='flex'>
            <MuiThemeProvider>
              <aside className=''>Side bar</aside>
              <ScrollTopHolder>
                <Suspense fallback={<Loading />}>
                  {children}
                </Suspense>
              </ScrollTopHolder>
            </MuiThemeProvider>
          </main>
        </Providers>
      </body>
    </html>
  );
}
