import type { Metadata } from "next";
import "./globals.css";
import MuiThemeProvider from '@jsc/theme/MuiThemeProvider';

import fonts from '@jsc//theme/font';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={fonts.default.variable}>
        <MuiThemeProvider>
          {children}
        </MuiThemeProvider>
      </body>
    </html>
  );
}
